//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP4                     162
#define IDB_ROLE1                       162
#define IDB_ROLE_TEST                   163
#define IDB_GATE1                       165
#define IDB_PNG1                        166
#define IDB_BITMAP3                     175
#define IDB_FLOOR_1                     175
#define IDB_BITMAP5                     176
#define IDB_WALL_1                      176
#define IDB_CH1_0                       177
#define IDB_CH1_1                       180
#define IDB_CH1_2                       181
#define IDB_CH1_3                       182
#define IDB_CH1_4                       183
#define IDB_CH1_5                       184
#define IDB_CH1_6                       185
#define IDB_CH1_7                       186
#define IDB_CH1_8                       187
#define IDB_enemy0_0                    188
#define IDB_enemy0_1                    189
#define IDB_enemy0_2                    190
#define IDB_enemy0_3                    191
#define IDB_enemy0_4                    192
#define IDB_enemy0_5                    193
#define IDB_enemy0_die                  194
#define IDB_enemy1_0                    195
#define IDB_enemy1_1                    196
#define IDB_enemy1_2                    197
#define IDB_enemy1_3                    198
#define IDB_enemy1_4                    199
#define IDB_enemy1_5                    200
#define IDB_enemy1_die                  201
#define IDB_enemy2_0                    202
#define IDB_enemy2_1                    203
#define IDB_enemy2_2                    204
#define IDB_enemy2_3                    205
#define IDB_enemy2_4                    206
#define IDB_enemy2_5                    207
#define IDB_enemy2_6                    208
#define IDB_enemy2_7                    209
#define IDB_BITMAP15                    210
#define IDB_enemy2_die                  210
#define IDB_CH1_0_L                     211
#define IDB_CH1_1_L                     212
#define IDB_CH1_2_L                     213
#define IDB_CH1_3_L                     214
#define IDB_CH1_4_L                     215
#define IDB_CH1_5_L                     216
#define IDB_CH1_6_L                     217
#define IDB_BITMAP13                    218
#define IDB_CH1_7_L                     218
#define IDB_weapon1                     219
#define IDB_BITMAP7                     220
#define IDB_weapon1_l                   220
#define IDB_Bullet1                     221
#define IDB_Bullet_e                    222
#define IDB_Bullet2                     223
#define IDB_BITMAP10                    224
#define IDB_Bullet3                     224
#define IDB_Bullet0                     225
#define IDB_BITMAP6                     226
#define IDB_BITMAP8                     227
#define IDB_BITMAP9                     228
#define IDB_BITMAP11                    229
#define IDB_BITMAP12                    230
#define IDB_BITMAP14                    231
#define IDB_BITMAP16                    232
#define IDB_BITMAP17                    233
#define IDB_BITMAP18                    234
#define IDB_BITMAP19                    235
#define IDB_BITMAP20                    236
#define IDB_BITMAP21                    237
#define IDB_BITMAP22                    238
#define IDB_BITMAP23                    239
#define IDB_BITMAP24                    240
#define IDB_BITMAP25                    241
#define IDB_BITMAP26                    242
#define IDB_BITMAP27                    243
#define IDB_BITMAP28                    244
#define IDB_BITMAP29                    245
#define IDB_ENEMY0_4_L                  246
#define IDB_ENEMY0_0_L                  247
#define IDB_enemy0_0_                   247
#define IDB_CH1_DIE                     248
#define IDB_ENEMY0_1_L                  249
#define IDB_ENEMY0_2_L                  250
#define IDB_ENEMY0_3_L                  251
#define IDB_BITMAP31                    253
#define IDB_enemy0_1_                   253
#define IDB_BITMAP32                    254
#define IDB_BITMAP33                    255
#define IDB_BITMAP34                    256
#define IDB_BITMAP35                    257
#define IDB_BITMAP36                    258
#define IDB_BITMAP37                    259
#define IDB_BITMAP38                    260
#define IDB_BITMAP39                    261
#define IDB_BITMAP40                    262
#define IDB_BITMAP41                    263
#define IDB_BITMAP42                    264
#define IDB_BITMAP43                    265
#define IDB_BITMAP44                    266
#define IDB_BITMAP45                    267
#define IDB_BITMAP46                    268
#define IDB_BITMAP47                    269
#define IDB_BITMAP48                    270
#define IDB_BITMAP49                    271
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
